// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYiVbHmf9zPrnQ5nQr5d5oVFPMtJJfkqU',
    appId: '1:685730525649:web:103daea7da8288cf0db0f0',
    messagingSenderId: '685730525649',
    projectId: 'flutter-startup-5f653',
    authDomain: 'flutter-startup-5f653.firebaseapp.com',
    storageBucket: 'flutter-startup-5f653.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtQgCHmiv0mnja4XmCzkWLT6trwebq_oA',
    appId: '1:685730525649:android:37da891595772ad50db0f0',
    messagingSenderId: '685730525649',
    projectId: 'flutter-startup-5f653',
    storageBucket: 'flutter-startup-5f653.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQqrXecAfirVgmYq7sQJp_cvArbZaAlME',
    appId: '1:685730525649:ios:a7d20ff613531baa0db0f0',
    messagingSenderId: '685730525649',
    projectId: 'flutter-startup-5f653',
    storageBucket: 'flutter-startup-5f653.appspot.com',
    iosBundleId: 'com.example.flutterIristagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQqrXecAfirVgmYq7sQJp_cvArbZaAlME',
    appId: '1:685730525649:ios:a7d20ff613531baa0db0f0',
    messagingSenderId: '685730525649',
    projectId: 'flutter-startup-5f653',
    storageBucket: 'flutter-startup-5f653.appspot.com',
    iosBundleId: 'com.example.flutterIristagram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYiVbHmf9zPrnQ5nQr5d5oVFPMtJJfkqU',
    appId: '1:685730525649:web:fa080eea313426d50db0f0',
    messagingSenderId: '685730525649',
    projectId: 'flutter-startup-5f653',
    authDomain: 'flutter-startup-5f653.firebaseapp.com',
    storageBucket: 'flutter-startup-5f653.appspot.com',
  );
}
